name: Post PRs and issues to Teams

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify
        uses: davidwengier/PostAdaptiveCard@v1.0.0
        if: github.repository == 'dotnet/project-system-tools' && github.actor != 'dmonroym'
        with:
          webhook-uri: ${{ secrets.TeamsWebhook }}
